global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'snake-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /metrics

  - job_name: 'snake-frontend'
    scrape_interval: 30s
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics  